---
 - name: install apache2
   become: true
   apt: 
      name: ["apache2"]
      state: latest
      update_cache: true

 - name: give write permissions 
   become: true 
   shell: chmod -R 775 /var/www/html    

 - name: install index page
   become: true
   copy:
     src: index.html
     dest: /var/www/html/index.html
     backup: yes